StartupEvents.registry('shincolle_kai:ship_attribute', event => {
  event.create('kubejs:gametest_attribute')
    .translationKey('ship_attribute.kubejs.gametest_attribute')
    .raw(2)
    .equipment(3)
    .morale(4)
    .potion(5)
    .formation(6)
    .scaledAdditive(true)
    .minimum(0)
    .maximum(100)
    .scaleGroup('hit')
    .displayFormat('percent')
    .enchantRule('weapon-additive')
    .enchantEffectSource('shincolle_kai:hit')
})
